package com.hiccup.domain;

public class Player {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_player.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_player.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_player.energy
     *
     * @mbggenerated
     */
    private Integer energy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_player.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_player.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_player.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_player.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_player.id
     *
     * @return the value of t_player.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_player.id
     *
     * @param id the value for t_player.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_player.user_id
     *
     * @return the value of t_player.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_player.user_id
     *
     * @param userId the value for t_player.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_player.energy
     *
     * @return the value of t_player.energy
     *
     * @mbggenerated
     */
    public Integer getEnergy() {
        return energy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_player.energy
     *
     * @param energy the value for t_player.energy
     *
     * @mbggenerated
     */
    public void setEnergy(Integer energy) {
        this.energy = energy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_player.url
     *
     * @return the value of t_player.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_player.url
     *
     * @param url the value for t_player.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_player.title
     *
     * @return the value of t_player.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_player.title
     *
     * @param title the value for t_player.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_player.status
     *
     * @return the value of t_player.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_player.status
     *
     * @param status the value for t_player.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_player.description
     *
     * @return the value of t_player.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_player.description
     *
     * @param description the value for t_player.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }
}